// Autogenerated code. Do not edit.

// This source code is dual-licensed under the Apache License, version
// 2.0, and the Mozilla Public License, version 1.1.
//
// The APL v2.0:
//
//---------------------------------------------------------------------------
//   Copyright (c) 2007-2016 Pivotal Software, Inc.
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
//---------------------------------------------------------------------------
//
// The MPL v1.1:
//
//---------------------------------------------------------------------------
//   The contents of this file are subject to the Mozilla Public License
//   Version 1.1 (the "License"); you may not use this file except in
//   compliance with the License. You may obtain a copy of the License at
//   http://www.rabbitmq.com/mpl.html
//
//   Software distributed under the License is distributed on an "AS IS"
//   basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
//   License for the specific language governing rights and limitations
//   under the License.
//
//   The Original Code is RabbitMQ.
//
//   The Initial Developer of the Original Code is Pivotal Software, Inc.
//   Copyright (c) 2007-2016 Pivotal Software, Inc.  All rights reserved.
//---------------------------------------------------------------------------

using RabbitMQ.Client.Exceptions;
namespace RabbitMQ.Client.Framing.Impl
{
    using RabbitMQ.Client.Framing;

    public class Model : RabbitMQ.Client.Impl.ModelBase
    {
        public Model(RabbitMQ.Client.Impl.ISession session) : base(session) { }
        public Model(RabbitMQ.Client.Impl.ISession session, RabbitMQ.Client.ConsumerWorkService workService) : base(session, workService) { }
        public override void ConnectionTuneOk(
          ushort @channelMax,
          uint @frameMax,
          ushort @heartbeat)
        {
            ModelSend(new ConnectionTuneOk(@channelMax,@frameMax,@heartbeat), null, null);
        }
        public override void _Private_BasicCancel(
          string @consumerTag,
          bool @nowait)
        {
            ModelSend(new BasicCancel(consumerTag, nowait), null, null);
        }
        public override void _Private_BasicConsume(
          string @queue,
          string @consumerTag,
          BasicConsumeFlags settings ,
          System.Collections.Generic.IDictionary<string, object> @arguments)
        {
            ModelSend(new BasicConsume(0, queue, consumerTag, settings, arguments), null, null);
        }
        public override void _Private_BasicGet(
          string @queue,
          bool @autoAck)
        {
            ModelSend(new BasicGet(0, queue, autoAck), null, null);
        }
        public override void _Private_BasicPublish(
          string @exchange,
          string @routingKey,
          bool @mandatory,
          RabbitMQ.Client.IBasicProperties @basicProperties,
          byte[] @body)
        {
            ModelSend(new BasicPublish(0, exchange, routingKey, mandatory ? BasicPublishFlags.Mandatory : BasicPublishFlags.None), (BasicProperties)basicProperties, body);
        }
        public override void _Private_BasicRecover(bool @requeue)
        {
            ModelSend(new BasicRecover(requeue), null, null);
        }
        public override void _Private_ChannelClose(
          ushort @replyCode,
          string @replyText,
          ushort @classId,
          ushort @methodId)
        {
            ModelSend(new ChannelClose(replyCode, replyText, classId, methodId), null, null);
        }
        public override void _Private_ChannelCloseOk()
        {
            ModelSend(new ChannelCloseOk(), null, null);
        }
        public override void _Private_ChannelFlowOk(bool @active)
        {
            ModelSend(new ChannelFlowOk(active), null, null);
        }
        public override void _Private_ChannelOpen(
          string @outOfBand)
        {
            IMethod __repBase = ModelRpc(new ChannelOpen(outOfBand), null, null);
            if (!(__repBase is ChannelOpenOk __rep)) throw new UnexpectedMethodException(__repBase);
        }
        public override void _Private_ConfirmSelect(
          bool @nowait)
        {
            ConfirmSelect __req = new ConfirmSelect(nowait);
            if (nowait)
            {
                ModelSend(__req, null, null);
                return;
            }
            IMethod __repBase = ModelRpc(__req, null, null);
            if (!(__repBase is ConfirmSelectOk __rep)) throw new UnexpectedMethodException(__repBase);
        }
        public override void _Private_ConnectionClose(
          ushort @replyCode,
          string @replyText,
          ushort @classId,
          ushort @methodId)
        {
            ConnectionClose __req = new ConnectionClose(replyCode, replyText, classId, methodId);
            IMethod __repBase = ModelRpc(__req, null, null);
            if (!(__repBase is ConnectionCloseOk __rep)) throw new UnexpectedMethodException(__repBase);
        }
        public override void _Private_ConnectionCloseOk()
        {
            ModelSend(new ConnectionCloseOk(), null, null);
        }
        public override void _Private_ConnectionOpen(
          string @virtualHost,
          string @capabilities,
          bool @insist)
        {
            ModelSend(new ConnectionOpen(@virtualHost, @capabilities, @insist), null, null);
        }
        public override void _Private_ConnectionSecureOk(
          string @response)
        {
            ModelSend(new ConnectionSecureOk(response), null, null);
        }
        public override void _Private_ConnectionStartOk(
          System.Collections.Generic.IDictionary<string, object> @clientProperties,
          string @mechanism,
          string @response,
          string @locale)
        {
            ModelSend(new ConnectionStartOk(clientProperties, mechanism, response, locale), null, null);
        }
        public override void _Private_ExchangeBind(
          string @destination,
          string @source,
          string @routingKey,
          bool @nowait,
          System.Collections.Generic.IDictionary<string, object> @arguments)
        {
            ExchangeBind __req = new ExchangeBind(0, destination, source, routingKey, nowait, arguments);
            if (nowait)
            {
                ModelSend(__req, null, null);
                return;
            }
            IMethod __repBase = ModelRpc(__req, null, null);
            if (!(__repBase is ExchangeBindOk __rep)) throw new UnexpectedMethodException(__repBase);
        }
        public override void _Private_ExchangeDeclare(
          string @exchange,
          string @type,
          ExchangeDeclareFlags flag,
          System.Collections.Generic.IDictionary<string, object> @arguments)
        {
            ExchangeDeclare __req = new ExchangeDeclare(0, exchange, type, flag, arguments);
            if ((flag & ExchangeDeclareFlags.NoWait) == ExchangeDeclareFlags.NoWait)
            {
                ModelSend(__req, null, null);
                return;
            }
            IMethod __repBase = ModelRpc(__req, null, null);
            if (!(__repBase is ExchangeDeclareOk __rep)) throw new UnexpectedMethodException(__repBase);
        }
        public override void _Private_ExchangeDelete(
          string @exchange,
          ExchangeDeleteFlags flag)
        {
            ExchangeDelete __req = new ExchangeDelete(0, exchange, flag);
            if ((flag & ExchangeDeleteFlags.NoWait) == ExchangeDeleteFlags.NoWait)
            {
                ModelSend(__req, null, null);
                return;
            }
            IMethod __repBase = ModelRpc(__req, null, null);
            if (!(__repBase is ExchangeDeleteOk __rep)) throw new UnexpectedMethodException(__repBase);
        }
        public override void _Private_ExchangeUnbind(
          string @destination,
          string @source,
          string @routingKey,
          bool @nowait,
          System.Collections.Generic.IDictionary<string, object> @arguments)
        {
            ExchangeUnbind __req = new ExchangeUnbind(0, destination, source, routingKey, nowait, arguments);
            if (nowait)
            {
                ModelSend(__req, null, null);
                return;
            }
            IMethod __repBase = ModelRpc(__req, null, null);
            if (!(__repBase is ExchangeUnbindOk __rep)) throw new UnexpectedMethodException(__repBase);
        }
        public override void _Private_QueueBind(
          string @queue,
          string @exchange,
          string @routingKey,
          bool @nowait,
          System.Collections.Generic.IDictionary<string, object> @arguments)
        {
            QueueBind __req = new QueueBind(0, queue, exchange, routingKey, nowait, arguments);
            if (nowait)
            {
                ModelSend(__req, null, null);
                return;
            }
            IMethod __repBase = ModelRpc(__req, null, null);
            if (!(__repBase is QueueBindOk __rep)) throw new UnexpectedMethodException(__repBase);
        }
        public override void _Private_QueueDeclare(
          string @queue,
          QueueDeclareFlags flag,
          System.Collections.Generic.IDictionary<string, object> @arguments)
        {
            ModelSend(new QueueDeclare(0, @queue, flag, @arguments), null, null);
        }
        public override uint _Private_QueueDelete(
          string @queue,
          QueueDeleteFlags flag)
        {
            QueueDelete __req = new QueueDelete(0,@queue, flag);
            if ((flag & QueueDeleteFlags.NoWait) == QueueDeleteFlags.NoWait)
            {
                ModelSend(__req, null, null);
                return 0xFFFFFFFF;
            }
            IMethod __repBase = ModelRpc(__req, null, null);
            if (!(__repBase is QueueDeleteOk __rep)) throw new UnexpectedMethodException(__repBase);
            return __rep.MessageCount;
        }
        public override uint _Private_QueuePurge(
          string @queue,
          bool @nowait)
        {
            QueuePurge __req = new QueuePurge(0, @queue, @nowait);
            if (nowait)
            {
                ModelSend(__req, null, null);
                return 0xFFFFFFFF;
            }
            IMethod __repBase = ModelRpc(__req, null, null);
            if (!(__repBase is QueuePurgeOk __rep)) throw new UnexpectedMethodException(__repBase);
            return __rep.MessageCount;
        }
        public override void BasicAck(
          ulong @deliveryTag,
          bool @multiple)
        {
            ModelSend(new BasicAck(deliveryTag, multiple), null, null);
        }
        public override void BasicNack(
          ulong @deliveryTag,
          BasicNackFlags settings)
        {
            ModelSend(new BasicNack(deliveryTag, settings), null, null);
        }
        public override void BasicQos(
          uint @prefetchSize,
          ushort @prefetchCount,
          bool @global)
        {
            IMethod __repBase = ModelRpc(new BasicQos(@prefetchSize, @prefetchCount, @global), null, null);
            if (!(__repBase is BasicQosOk __rep)) throw new UnexpectedMethodException(__repBase);
        }
        public override void BasicRecoverAsync(
          bool @requeue)
        {
            ModelSend(new BasicRecoverAsync(@requeue), null, null);
        }
        public override void BasicReject(
          ulong @deliveryTag,
          bool @requeue)
        {
            ModelSend(new BasicReject(deliveryTag, requeue), null, null);
        }
        public override RabbitMQ.Client.Impl.BasicProperties CreateBasicProperties()
        {
            return new BasicProperties();
        }
        public override void QueueUnbind(
          string @queue,
          string @exchange,
          string @routingKey,
          System.Collections.Generic.IDictionary<string, object> @arguments)
        {
            QueueUnbind __req = new QueueUnbind(0,@queue,@exchange,@routingKey,@arguments);
            IMethod __repBase = ModelRpc(__req, null, null);
            if (!(__repBase is QueueUnbindOk __rep)) throw new UnexpectedMethodException(__repBase);
        }
        public override void TxCommit()
        {
            TxCommit __req = new TxCommit();
            IMethod __repBase = ModelRpc(__req, null, null);
            if (!(__repBase is TxCommitOk __rep)) throw new UnexpectedMethodException(__repBase);
        }
        public override void TxRollback()
        {
            TxRollback __req = new TxRollback();
            IMethod __repBase = ModelRpc(__req, null, null);
            if (!(__repBase is TxRollbackOk __rep)) throw new UnexpectedMethodException(__repBase);
        }
        public override void TxSelect()
        {
            TxSelect __req = new TxSelect();
            IMethod __repBase = ModelRpc(__req, null, null);
            if (!(__repBase is TxSelectOk __rep))
            {
                throw new UnexpectedMethodException(__repBase);
            }
        }
        public override bool DispatchAsynchronous(RabbitMQ.Client.Impl.Command cmd)
        {
            IMethod __method = (IMethod)cmd.Method;
            switch ((__method.ProtocolClassId << 16) | __method.ProtocolMethodId)
            {
                case 3932240:
                    {
                        BasicAck __impl = (BasicAck)__method;
                        HandleBasicAck(__impl.m_deliveryTag,__impl.m_multiple);
                        return true;
                    }
                case 3932190:
                    {
                        BasicCancel __impl = (BasicCancel)__method;
                        HandleBasicCancel(__impl.ConsumerTag,__impl.Nowait);
                        return true;
                    }
                case 3932191:
                    {
                        BasicCancelOk __impl = (BasicCancelOk)__method;
                        HandleBasicCancelOk(__impl.ConsumerTag);
                        return true;
                    }
                case 3932181:
                    {
                        BasicConsumeOk __impl = (BasicConsumeOk)__method;
                        HandleBasicConsumeOk(__impl.ConsumerTag);
                        return true;
                    }
                case 3932220:
                    {
                        BasicDeliver __impl = (BasicDeliver)__method;
                        HandleBasicDeliver(
                          __impl.ConsumerTag,
                          __impl.DeliveryTag,
                          __impl.Redelivered,
                          __impl.Exchange,
                          __impl.RoutingKey,
                          cmd.Header,
                          cmd.Body);
                        return true;
                    }
                case 3932232:
                    {
                        HandleBasicGetEmpty();
                        return true;
                    }
                case 3932231:
                    {
                        BasicGetOk __impl = (BasicGetOk)__method;
                        HandleBasicGetOk(
                          __impl.DeliveryTag,
                          __impl.Redelivered,
                          __impl.Exchange,
                          __impl.RoutingKey,
                          __impl.MessageCount,
                          cmd.Header,
                          cmd.Body);
                        return true;
                    }
                case 3932280:
                    {
                        BasicNack __impl = (BasicNack)__method;
                        HandleBasicNack(
                          __impl.DeliveryTag,
                          __impl.Settings);
                        return true;
                    }
                case 3932271:
                    {
                        HandleBasicRecoverOk();
                        return true;
                    }
                case 3932210:
                    {
                        BasicReturn __impl = (BasicReturn)__method;
                        HandleBasicReturn(
                          __impl.ReplyCode,
                          __impl.ReplyText,
                          __impl.Exchange,
                          __impl.RoutingKey,
                          cmd.Header,
                          cmd.Body);
                        return true;
                    }
                case 1310760:
                    {
                        ChannelClose __impl = (ChannelClose)__method;
                        HandleChannelClose(
                          __impl.ReplyCode,
                          __impl.ReplyText,
                          __impl.ProtocolClassId,
                          __impl.ProtocolMethodId);
                        return true;
                    }
                case 1310761:
                    {
                        HandleChannelCloseOk();
                        return true;
                    }
                case 1310740:
                    {
                        ChannelFlow __impl = (ChannelFlow)__method;
                        HandleChannelFlow(
                          __impl.Active);
                        return true;
                    }
                case 655420:
                    {
                        ConnectionBlocked __impl = (ConnectionBlocked)__method;
                        HandleConnectionBlocked(
                          __impl.Reason);
                        return true;
                    }
                case 655410:
                    {
                        ConnectionClose __impl = (ConnectionClose)__method;
                        HandleConnectionClose(
                          __impl.ReplyCode,
                          __impl.ReplyText,
                          __impl.ProtocolClassId,
                          __impl.ProtocolMethodId);
                        return true;
                    }
                case 655401:
                    {
                        ConnectionOpenOk __impl = (ConnectionOpenOk)__method;
                        HandleConnectionOpenOk(
                          __impl.Reserved1);
                        return true;
                    }
                case 655380:
                    {
                        ConnectionSecure __impl = (ConnectionSecure)__method;
                        HandleConnectionSecure(
                          __impl.Challenge);
                        return true;
                    }
                case 655370:
                    {
                        ConnectionStart __impl = (ConnectionStart)__method;
                        HandleConnectionStart(
                          __impl.VersionMajor,
                          __impl.VersionMinor,
                          __impl.ServerProperties,
                          __impl.Mechanisms,
                          __impl.Locales);
                        return true;
                    }
                case 655390:
                    {
                        ConnectionTune __impl = (ConnectionTune)__method;
                        HandleConnectionTune(
                          __impl.ChannelMax,
                          __impl.FrameMax,
                          __impl.Heartbeat);
                        return true;
                    }
                case 655421:
                    {
                        HandleConnectionUnblocked();
                        return true;
                    }
                case 3276811:
                    {
                        QueueDeclareOk __impl = (QueueDeclareOk)__method;
                        HandleQueueDeclareOk(
                          __impl.Queue,
                          __impl.MessageCount,
                          __impl.ConsumerCount);
                        return true;
                    }
                default: return false;
            }
        }
    }
}