// Autogenerated code. Do not edit.

// This source code is dual-licensed under the Apache License, version
// 2.0, and the Mozilla Public License, version 1.1.
//
// The APL v2.0:
//
//---------------------------------------------------------------------------
//   Copyright (c) 2007-2016 Pivotal Software, Inc.
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
//---------------------------------------------------------------------------
//
// The MPL v1.1:
//
//---------------------------------------------------------------------------
//   The contents of this file are subject to the Mozilla Public License
//   Version 1.1 (the "License"); you may not use this file except in
//   compliance with the License. You may obtain a copy of the License at
//   http://www.rabbitmq.com/mpl.html
//
//   Software distributed under the License is distributed on an "AS IS"
//   basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
//   License for the specific language governing rights and limitations
//   under the License.
//
//   The Original Code is RabbitMQ.
//
//   The Initial Developer of the Original Code is Pivotal Software, Inc.
//   Copyright (c) 2007-2016 Pivotal Software, Inc.  All rights reserved.
//---------------------------------------------------------------------------

using RabbitMQ.Client.Impl;
using RabbitMQ.Util;
namespace RabbitMQ.Client.Framing.Impl
{
    using RabbitMQ.Client.Framing;
    using System;

    /// <summary>Autogenerated type. Private implementation class - do not use directly.</summary>
    public class BasicDeliver : RabbitMQ.Client.Impl.MethodBase, IBasicDeliver
    {
        public const ushort ClassId = 60;
        public const ushort MethodId = 60;

        public string m_consumerTag;
        public ulong m_deliveryTag;
        public bool m_redelivered;
        public string m_exchange;
        public string m_routingKey;

        string IBasicDeliver.ConsumerTag { get { return m_consumerTag; } }
        ulong IBasicDeliver.DeliveryTag { get { return m_deliveryTag; } }
        bool IBasicDeliver.Redelivered { get { return m_redelivered; } }
        string IBasicDeliver.Exchange { get { return m_exchange; } }
        string IBasicDeliver.RoutingKey { get { return m_routingKey; } }

        public BasicDeliver() { }
        public BasicDeliver(
          string initConsumerTag,
          ulong initDeliveryTag,
          bool initRedelivered,
          string initExchange,
          string initRoutingKey)
        {
            m_consumerTag = initConsumerTag;
            m_deliveryTag = initDeliveryTag;
            m_redelivered = initRedelivered;
            m_exchange = initExchange;
            m_routingKey = initRoutingKey;
        }

        public override ushort ProtocolClassId { get { return 60; } }
        public override ushort ProtocolMethodId { get { return 60; } }
        public override string ProtocolMethodName { get { return "basic.deliver"; } }
        public override bool HasContent { get { return true; } }

        public override void ReadArgumentsFrom(ArraySegmentSequence reader)
        {
            m_consumerTag = reader.ReadShortString();
            m_deliveryTag = reader.ReadUInt64();
            m_redelivered = Convert.ToBoolean(reader.ReadByte());
            m_exchange = reader.ReadShortString();
            m_routingKey = reader.ReadShortString();
        }

        public override void WriteArgumentsTo(FrameBuilder writer)
        {
            writer.WriteShortString(m_consumerTag);
            writer.WriteUInt64(m_deliveryTag);
            writer.WriteByte(Convert.ToByte(m_redelivered));
            writer.WriteShortString(m_exchange);
            writer.WriteShortString(m_routingKey);
        }

        public override void AppendArgumentDebugStringTo(System.Text.StringBuilder sb)
        {
            sb.Append("(");
            sb.Append(m_consumerTag); sb.Append(",");
            sb.Append(m_deliveryTag); sb.Append(",");
            sb.Append(m_redelivered); sb.Append(",");
            sb.Append(m_exchange); sb.Append(",");
            sb.Append(m_routingKey);
            sb.Append(")");
        }
    }
}