// Autogenerated code. Do not edit.

// This source code is dual-licensed under the Apache License, version
// 2.0, and the Mozilla Public License, version 1.1.
//
// The APL v2.0:
//
//---------------------------------------------------------------------------
//   Copyright (c) 2007-2016 Pivotal Software, Inc.
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
//---------------------------------------------------------------------------
//
// The MPL v1.1:
//
//---------------------------------------------------------------------------
//   The contents of this file are subject to the Mozilla Public License
//   Version 1.1 (the "License"); you may not use this file except in
//   compliance with the License. You may obtain a copy of the License at
//   http://www.rabbitmq.com/mpl.html
//
//   Software distributed under the License is distributed on an "AS IS"
//   basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
//   License for the specific language governing rights and limitations
//   under the License.
//
//   The Original Code is RabbitMQ.
//
//   The Initial Developer of the Original Code is Pivotal Software, Inc.
//   Copyright (c) 2007-2016 Pivotal Software, Inc.  All rights reserved.
//---------------------------------------------------------------------------

using RabbitMQ.Client.Impl;
using RabbitMQ.Util;
namespace RabbitMQ.Client.Framing.Impl
{
    using RabbitMQ.Client.Framing;
    using System;

    /// <summary>Autogenerated type. Private implementation class - do not use directly.</summary>
    public class BasicCancel : IMethod, IBasicCancel
    {
        public const ushort ClassId = 60;
        public const ushort MethodId = 30;

        private string m_consumerTag;
        private bool m_nowait;

        public string ConsumerTag { get { return m_consumerTag; } }
        public bool Nowait { get { return m_nowait; } }

        public BasicCancel() { }

        public BasicCancel(
          string initConsumerTag,
          bool initNowait)
        {
            m_consumerTag = initConsumerTag;
            m_nowait = initNowait;
        }

        public ushort ProtocolClassId { get { return 60; } }
        public ushort ProtocolMethodId { get { return 30; } }
        public string ProtocolMethodName { get { return "basic.cancel"; } }
        public bool HasContent { get { return false; } }

        public void ReadArgumentsFrom(ArraySegmentSequence reader)
        {
            m_consumerTag = reader.ReadShortString();
            m_nowait = Convert.ToBoolean(reader.ReadByte());
        }


        public void WriteArgumentsTo(Span<byte> writer, out int written)
        {
            NetworkBinaryWriter1.WriteShortString(writer, m_consumerTag, out int written1);
            NetworkBinaryWriter1.WriteByte(writer.Slice(written1), Convert.ToByte(m_nowait), out int written2);
            written = written1 + written2;
        }
        public int EstimateSize()
        {
            return 2 +
                System.Text.Encoding.UTF8.GetByteCount(m_consumerTag );
        }

        public bool CompareClassAndMethod(int classId, int methodId){return ClassId == classId && MethodId == methodId;}  public void AppendArgumentDebugStringTo(System.Text.StringBuilder sb)
        {
            sb.Append("(");
            sb.Append(m_consumerTag); sb.Append(",");
            sb.Append(m_nowait);
            sb.Append(")");
        }
    }
}