// Autogenerated code. Do not edit.

// This source code is dual-licensed under the Apache License, version
// 2.0, and the Mozilla Public License, version 1.1.
//
// The APL v2.0:
//
//---------------------------------------------------------------------------
//   Copyright (c) 2007-2016 Pivotal Software, Inc.
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
//---------------------------------------------------------------------------
//
// The MPL v1.1:
//
//---------------------------------------------------------------------------
//   The contents of this file are subject to the Mozilla Public License
//   Version 1.1 (the "License"); you may not use this file except in
//   compliance with the License. You may obtain a copy of the License at
//   http://www.rabbitmq.com/mpl.html
//
//   Software distributed under the License is distributed on an "AS IS"
//   basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
//   License for the specific language governing rights and limitations
//   under the License.
//
//   The Original Code is RabbitMQ.
//
//   The Initial Developer of the Original Code is Pivotal Software, Inc.
//   Copyright (c) 2007-2016 Pivotal Software, Inc.  All rights reserved.
//---------------------------------------------------------------------------

using RabbitMQ.Client.Impl;
using RabbitMQ.Util;
namespace RabbitMQ.Client.Framing.Impl
{
    using RabbitMQ.Client.Framing;

    /// <summary>Autogenerated type. Private implementation class - do not use directly.</summary>
    public class BasicPublish : RabbitMQ.Client.Impl.MethodBase, IBasicPublish
    {
        public const ushort ClassId = 60;
        public const ushort MethodId = 40;

        public ushort m_reserved1;
        public string m_exchange;
        public string m_routingKey;
        public bool m_mandatory;
        public bool m_immediate;

        ushort IBasicPublish.Reserved1 { get { return m_reserved1; } }
        string IBasicPublish.Exchange { get { return m_exchange; } }
        string IBasicPublish.RoutingKey { get { return m_routingKey; } }
        bool IBasicPublish.Mandatory { get { return m_mandatory; } }
        bool IBasicPublish.Immediate { get { return m_immediate; } }

        public BasicPublish() { }
        public BasicPublish(
          ushort initReserved1,
          string initExchange,
          string initRoutingKey,
          bool initMandatory,
          bool initImmediate)
        {
            m_reserved1 = initReserved1;
            m_exchange = initExchange;
            m_routingKey = initRoutingKey;
            m_mandatory = initMandatory;
            m_immediate = initImmediate;
        }

        public override ushort ProtocolClassId { get { return 60; } }
        public override ushort ProtocolMethodId { get { return 40; } }
        public override string ProtocolMethodName { get { return "basic.publish"; } }
        public override bool HasContent { get { return true; } }

        public override void ReadArgumentsFrom(ArraySegmentSequence reader)
        {
            m_reserved1 = reader.ReadUInt16();
            m_exchange = reader.ReadShortString();
            m_routingKey = reader.ReadShortString();

            BasicPublishFlags flags = (BasicPublishFlags)reader.ReadByte();

            m_mandatory = (flags & BasicPublishFlags.Mandatory) == BasicPublishFlags.Mandatory;
            m_immediate = (flags & BasicPublishFlags.Immediate) == BasicPublishFlags.Immediate;
        }

        public override void WriteArgumentsTo(FrameBuilder writer)
        {
            writer.WriteUInt16(m_reserved1);
            writer.WriteShortString(m_exchange);
            writer.WriteShortString(m_routingKey);

            BasicPublishFlags flags = BasicPublishFlags.None;
            if (m_mandatory) flags |= BasicPublishFlags.Mandatory;
            if (m_immediate) flags |= BasicPublishFlags.Immediate;

            writer.WriteByte((byte)flags);
            //m_mandatory);
            //writer.WriteBit(m_immediate);
        }

        public override void AppendArgumentDebugStringTo(System.Text.StringBuilder sb)
        {
            sb.Append("(");
            sb.Append(m_reserved1); sb.Append(",");
            sb.Append(m_exchange); sb.Append(",");
            sb.Append(m_routingKey); sb.Append(",");
            sb.Append(m_mandatory); sb.Append(",");
            sb.Append(m_immediate);
            sb.Append(")");
        }
    }
}