// Autogenerated code. Do not edit.

// This source code is dual-licensed under the Apache License, version
// 2.0, and the Mozilla Public License, version 1.1.
//
// The APL v2.0:
//
//---------------------------------------------------------------------------
//   Copyright (c) 2007-2016 Pivotal Software, Inc.
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
//---------------------------------------------------------------------------
//
// The MPL v1.1:
//
//---------------------------------------------------------------------------
//   The contents of this file are subject to the Mozilla Public License
//   Version 1.1 (the "License"); you may not use this file except in
//   compliance with the License. You may obtain a copy of the License at
//   http://www.rabbitmq.com/mpl.html
//
//   Software distributed under the License is distributed on an "AS IS"
//   basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
//   License for the specific language governing rights and limitations
//   under the License.
//
//   The Original Code is RabbitMQ.
//
//   The Initial Developer of the Original Code is Pivotal Software, Inc.
//   Copyright (c) 2007-2016 Pivotal Software, Inc.  All rights reserved.
//---------------------------------------------------------------------------

using RabbitMQ.Client.Impl;
using RabbitMQ.Util;
namespace RabbitMQ.Client.Framing.Impl
{
    using RabbitMQ.Client.Framing;

    /// <summary>Autogenerated type. Private implementation class - do not use directly.</summary>
    public class BasicNack : RabbitMQ.Client.Impl.MethodBase, IBasicNack
    {
        public const ushort ClassId = 60;
        public const ushort MethodId = 120;

        public ulong m_deliveryTag;
        public bool m_multiple;
        public bool m_requeue;

        ulong IBasicNack.DeliveryTag { get { return m_deliveryTag; } }
        bool IBasicNack.Multiple { get { return m_multiple; } }
        bool IBasicNack.Requeue { get { return m_requeue; } }

        public BasicNack() { }
        public BasicNack(
          ulong initDeliveryTag,
          bool initMultiple,
          bool initRequeue)
        {
            m_deliveryTag = initDeliveryTag;
            m_multiple = initMultiple;
            m_requeue = initRequeue;
        }

        public override ushort ProtocolClassId { get { return 60; } }
        public override ushort ProtocolMethodId { get { return 120; } }
        public override string ProtocolMethodName { get { return "basic.nack"; } }
        public override bool HasContent { get { return false; } }

        public override void ReadArgumentsFrom(ArraySegmentSequence reader)
        {
            m_deliveryTag = reader.ReadUInt64();

            BasicNackFlags flags = (BasicNackFlags) reader.ReadByte();

            m_multiple = (flags & BasicNackFlags.Multiple) == BasicNackFlags.Multiple;
            m_requeue = (flags & BasicNackFlags.Requeue) == BasicNackFlags.Requeue;
        }

        public override void WriteArgumentsTo(FrameBuilder writer)
        {
            writer.WriteUInt64(m_deliveryTag);

            BasicNackFlags flags = BasicNackFlags.None;
            if (m_multiple) flags |= BasicNackFlags.Multiple;
            if (m_requeue) flags |= BasicNackFlags.Requeue;

            writer.WriteByte((byte)flags);
            //writer.WriteBit(m_multiple);
            //writer.WriteBit(m_requeue);
        }

        public override void AppendArgumentDebugStringTo(System.Text.StringBuilder sb)
        {
            sb.Append("(");
            sb.Append(m_deliveryTag); sb.Append(",");
            sb.Append(m_multiple); sb.Append(",");
            sb.Append(m_requeue);
            sb.Append(")");
        }
    }
}