// Autogenerated code. Do not edit.

// This source code is dual-licensed under the Apache License, version
// 2.0, and the Mozilla Public License, version 1.1.
//
// The APL v2.0:
//
//---------------------------------------------------------------------------
//   Copyright (c) 2007-2016 Pivotal Software, Inc.
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
//---------------------------------------------------------------------------
//
// The MPL v1.1:
//
//---------------------------------------------------------------------------
//   The contents of this file are subject to the Mozilla Public License
//   Version 1.1 (the "License"); you may not use this file except in
//   compliance with the License. You may obtain a copy of the License at
//   http://www.rabbitmq.com/mpl.html
//
//   Software distributed under the License is distributed on an "AS IS"
//   basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
//   License for the specific language governing rights and limitations
//   under the License.
//
//   The Original Code is RabbitMQ.
//
//   The Initial Developer of the Original Code is Pivotal Software, Inc.
//   Copyright (c) 2007-2016 Pivotal Software, Inc.  All rights reserved.
//---------------------------------------------------------------------------

using RabbitMQ.Client.Impl;
using RabbitMQ.Util;
namespace RabbitMQ.Client.Framing.Impl
{
    using RabbitMQ.Client.Framing;
    using System;

    /// <summary>Autogenerated type. Private implementation class - do not use directly.</summary>
    public class BasicGetOk : IMethod, IBasicGetOk
    {
        public const ushort ClassId = 60;
        public const ushort MethodId = 71;

        private ulong m_deliveryTag;
        private bool m_redelivered;
        private string m_exchange;
        private string m_routingKey;
        private uint m_messageCount;

        public ulong DeliveryTag { get { return m_deliveryTag; } }
        public bool Redelivered { get { return m_redelivered; } }
        public string Exchange { get { return m_exchange; } }
        public string RoutingKey { get { return m_routingKey; } }
        public uint MessageCount { get { return m_messageCount; } }

        public BasicGetOk() { }
        public BasicGetOk(
          ulong initDeliveryTag,
          bool initRedelivered,
          string initExchange,
          string initRoutingKey,
          uint initMessageCount)
        {
            m_deliveryTag = initDeliveryTag;
            m_redelivered = initRedelivered;
            m_exchange = initExchange;
            m_routingKey = initRoutingKey;
            m_messageCount = initMessageCount;
        }

        public ushort ProtocolClassId { get { return 60; } }
        public ushort ProtocolMethodId { get { return 71; } }
        public string ProtocolMethodName { get { return "basic.get-ok"; } }
        public bool HasContent { get { return true; } }

        public void ReadArgumentsFrom(ArraySegmentSequence reader)
        {
            m_deliveryTag = reader.ReadUInt64();
            m_redelivered = Convert.ToBoolean(reader.ReadByte());
            m_exchange = reader.ReadShortString();
            m_routingKey = reader.ReadShortString();
            m_messageCount = reader.ReadUInt32();
        }

        public void WriteArgumentsTo(FrameBuilder writer)
        {
            writer.WriteUInt64(m_deliveryTag);
            writer.WriteByte(Convert.ToByte(m_redelivered));
            writer.WriteShortString(m_exchange);
            writer.WriteShortString(m_routingKey);
            writer.WriteUInt32(m_messageCount);
        }
        public void WriteArgumentsTo(ref Span<byte> writer, out int written)
        {
            NetworkBinaryWriter1.WriteUInt64(ref writer, m_deliveryTag, out int written1);
            NetworkBinaryWriter1.WriteByte(ref writer, Convert.ToByte(m_redelivered), out int written2);
            NetworkBinaryWriter1.WriteShortString(ref writer, m_exchange, out int written3);
            NetworkBinaryWriter1.WriteShortString(ref writer, m_routingKey, out int written4);
            NetworkBinaryWriter1.WriteUInt32(ref writer, m_messageCount, out int written5);
            written = written1 + written2 + written3 + written4 + written5;
        }
        public int EstimateSize()
        {
            return 15 +
                System.Text.Encoding.UTF8.GetByteCount(m_exchange ) +
                System.Text.Encoding.UTF8.GetByteCount(m_routingKey );
        }
        public void AppendArgumentDebugStringTo(System.Text.StringBuilder sb)
        {
            sb.Append("(");
            sb.Append(m_deliveryTag); sb.Append(",");
            sb.Append(m_redelivered); sb.Append(",");
            sb.Append(m_exchange); sb.Append(",");
            sb.Append(m_routingKey); sb.Append(",");
            sb.Append(m_messageCount);
            sb.Append(")");
        }
    }
}