// Autogenerated code. Do not edit.

// This source code is dual-licensed under the Apache License, version
// 2.0, and the Mozilla Public License, version 1.1.
//
// The APL v2.0:
//
//---------------------------------------------------------------------------
//   Copyright (c) 2007-2016 Pivotal Software, Inc.
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
//---------------------------------------------------------------------------
//
// The MPL v1.1:
//
//---------------------------------------------------------------------------
//   The contents of this file are subject to the Mozilla Public License
//   Version 1.1 (the "License"); you may not use this file except in
//   compliance with the License. You may obtain a copy of the License at
//   http://www.rabbitmq.com/mpl.html
//
//   Software distributed under the License is distributed on an "AS IS"
//   basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
//   License for the specific language governing rights and limitations
//   under the License.
//
//   The Original Code is RabbitMQ.
//
//   The Initial Developer of the Original Code is Pivotal Software, Inc.
//   Copyright (c) 2007-2016 Pivotal Software, Inc.  All rights reserved.
//---------------------------------------------------------------------------

using RabbitMQ.Client.Impl;
using RabbitMQ.Util;
namespace RabbitMQ.Client.Framing.Impl
{
    using RabbitMQ.Client.Framing;
    using System;

    /// <summary>Autogenerated type. Private implementation class - do not use directly.</summary>
    public class ExchangeBind : RabbitMQ.Client.Impl.MethodBase, IExchangeBind
    {
        public const ushort ClassId = 40;
        public const ushort MethodId = 30;

        public ushort m_reserved1;
        public string m_destination;
        public string m_source;
        public string m_routingKey;
        public bool m_nowait;
        public System.Collections.Generic.IDictionary<string, object> m_arguments;

        ushort IExchangeBind.Reserved1 { get { return m_reserved1; } }
        string IExchangeBind.Destination { get { return m_destination; } }
        string IExchangeBind.Source { get { return m_source; } }
        string IExchangeBind.RoutingKey { get { return m_routingKey; } }
        bool IExchangeBind.Nowait { get { return m_nowait; } }
        System.Collections.Generic.IDictionary<string, object> IExchangeBind.Arguments { get { return m_arguments; } }

        public ExchangeBind() { }
        public ExchangeBind(
          ushort initReserved1,
          string initDestination,
          string initSource,
          string initRoutingKey,
          bool initNowait,
          System.Collections.Generic.IDictionary<string, object> initArguments)
        {
            m_reserved1 = initReserved1;
            m_destination = initDestination;
            m_source = initSource;
            m_routingKey = initRoutingKey;
            m_nowait = initNowait;
            m_arguments = initArguments;
        }

        public override ushort ProtocolClassId { get { return 40; } }
        public override ushort ProtocolMethodId { get { return 30; } }
        public override string ProtocolMethodName { get { return "exchange.bind"; } }
        public override bool HasContent { get { return false; } }

        public override void ReadArgumentsFrom(ArraySegmentSequence reader)
        {
            m_reserved1 = reader.ReadUInt16();
            m_destination = reader.ReadShortString();
            m_source = reader.ReadShortString();
            m_routingKey = reader.ReadShortString();
            m_nowait = Convert.ToBoolean(reader.ReadByte());
            m_arguments = reader.ReadTable();
        }

        public override void WriteArgumentsTo(FrameBuilder writer)
        {
            writer.WriteUInt16(m_reserved1);
            writer.WriteShortString(m_destination);
            writer.WriteShortString(m_source);
            writer.WriteShortString(m_routingKey);
            writer.WriteByte(Convert.ToByte(m_nowait));
            writer.WriteTable(m_arguments);
        }

        public override void AppendArgumentDebugStringTo(System.Text.StringBuilder sb)
        {
            sb.Append("(");
            sb.Append(m_reserved1); sb.Append(",");
            sb.Append(m_destination); sb.Append(",");
            sb.Append(m_source); sb.Append(",");
            sb.Append(m_routingKey); sb.Append(",");
            sb.Append(m_nowait); sb.Append(",");
            sb.Append(m_arguments);
            sb.Append(")");
        }
    }
}