// Autogenerated code. Do not edit.

// This source code is dual-licensed under the Apache License, version
// 2.0, and the Mozilla Public License, version 1.1.
//
// The APL v2.0:
//
//---------------------------------------------------------------------------
//   Copyright (c) 2007-2016 Pivotal Software, Inc.
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
//---------------------------------------------------------------------------
//
// The MPL v1.1:
//
//---------------------------------------------------------------------------
//   The contents of this file are subject to the Mozilla Public License
//   Version 1.1 (the "License"); you may not use this file except in
//   compliance with the License. You may obtain a copy of the License at
//   http://www.rabbitmq.com/mpl.html
//
//   Software distributed under the License is distributed on an "AS IS"
//   basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
//   License for the specific language governing rights and limitations
//   under the License.
//
//   The Original Code is RabbitMQ.
//
//   The Initial Developer of the Original Code is Pivotal Software, Inc.
//   Copyright (c) 2007-2016 Pivotal Software, Inc.  All rights reserved.
//---------------------------------------------------------------------------

using RabbitMQ.Client.Impl;
using RabbitMQ.Util;
namespace RabbitMQ.Client.Framing.Impl
{
    using RabbitMQ.Client.Framing;

    /// <summary>Autogenerated type. Private implementation class - do not use directly.</summary>
    public class ExchangeDelete : IMethod, IExchangeDelete
    {
        public const ushort ClassId = 40;
        public const ushort MethodId = 20;

        private ushort m_reserved1;
        private string m_exchange;
        private bool m_ifUnused;
        private bool m_nowait;

        public ushort Reserved1 { get { return m_reserved1; } }
        public string Exchange { get { return m_exchange; } }
        public bool IfUnused { get { return m_ifUnused; } }
        public bool Nowait { get { return m_nowait; } }

        public ExchangeDelete() { }
        public ExchangeDelete(
          ushort initReserved1,
          string initExchange,
          bool initIfUnused,
          bool initNowait)
        {
            m_reserved1 = initReserved1;
            m_exchange = initExchange;
            m_ifUnused = initIfUnused;
            m_nowait = initNowait;
        }

        public ushort ProtocolClassId { get { return 40; } }
        public ushort ProtocolMethodId { get { return 20; } }
        public string ProtocolMethodName { get { return "exchange.delete"; } }
        public bool HasContent { get { return false; } }

        public void ReadArgumentsFrom(ArraySegmentSequence reader)
        {
            m_reserved1 = reader.ReadUInt16();
            m_exchange = reader.ReadShortString();

            ExchangeDeleteFlags flags = (ExchangeDeleteFlags)reader.ReadByte();

            m_ifUnused = (flags & ExchangeDeleteFlags.IfUnused) == ExchangeDeleteFlags.IfUnused;
            m_nowait = (flags & ExchangeDeleteFlags.NoWait) == ExchangeDeleteFlags.NoWait;
        }

        public void WriteArgumentsTo(FrameBuilder writer)
        {
            writer.WriteUInt16(m_reserved1);
            writer.WriteShortString(m_exchange);

            ExchangeDeleteFlags flags = ExchangeDeleteFlags.None;
            if (m_ifUnused) flags |= ExchangeDeleteFlags.IfUnused;
            if (m_nowait) flags |= ExchangeDeleteFlags.NoWait;

            writer.WriteByte((byte)flags);
        }

        public void AppendArgumentDebugStringTo(System.Text.StringBuilder sb)
        {
            sb.Append("(");
            sb.Append(m_reserved1); sb.Append(",");
            sb.Append(m_exchange); sb.Append(",");
            sb.Append(m_ifUnused); sb.Append(",");
            sb.Append(m_nowait);
            sb.Append(")");
        }
    }
}