// Autogenerated code. Do not edit.

// This source code is dual-licensed under the Apache License, version
// 2.0, and the Mozilla Public License, version 1.1.
//
// The APL v2.0:
//
//---------------------------------------------------------------------------
//   Copyright (c) 2007-2016 Pivotal Software, Inc.
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
//---------------------------------------------------------------------------
//
// The MPL v1.1:
//
//---------------------------------------------------------------------------
//   The contents of this file are subject to the Mozilla Public License
//   Version 1.1 (the "License"); you may not use this file except in
//   compliance with the License. You may obtain a copy of the License at
//   http://www.rabbitmq.com/mpl.html
//
//   Software distributed under the License is distributed on an "AS IS"
//   basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
//   License for the specific language governing rights and limitations
//   under the License.
//
//   The Original Code is RabbitMQ.
//
//   The Initial Developer of the Original Code is Pivotal Software, Inc.
//   Copyright (c) 2007-2016 Pivotal Software, Inc.  All rights reserved.
//---------------------------------------------------------------------------

using RabbitMQ.Client.Impl;
using RabbitMQ.Util;
namespace RabbitMQ.Client.Framing.Impl
{
    using RabbitMQ.Client.Framing;

    /// <summary>Autogenerated type. Private implementation class - do not use directly.</summary>
    public class QueueUnbind : RabbitMQ.Client.Impl.MethodBase, IQueueUnbind
    {
        public const ushort ClassId = 50;
        public const ushort MethodId = 50;

        public ushort m_reserved1;
        public string m_queue;
        public string m_exchange;
        public string m_routingKey;
        public System.Collections.Generic.IDictionary<string, object> m_arguments;

        ushort IQueueUnbind.Reserved1 { get { return m_reserved1; } }
        string IQueueUnbind.Queue { get { return m_queue; } }
        string IQueueUnbind.Exchange { get { return m_exchange; } }
        string IQueueUnbind.RoutingKey { get { return m_routingKey; } }
        System.Collections.Generic.IDictionary<string, object> IQueueUnbind.Arguments { get { return m_arguments; } }

        public QueueUnbind() { }
        public QueueUnbind(
          ushort initReserved1,
          string initQueue,
          string initExchange,
          string initRoutingKey,
          System.Collections.Generic.IDictionary<string, object> initArguments)
        {
            m_reserved1 = initReserved1;
            m_queue = initQueue;
            m_exchange = initExchange;
            m_routingKey = initRoutingKey;
            m_arguments = initArguments;
        }

        public override ushort ProtocolClassId { get { return 50; } }
        public override ushort ProtocolMethodId { get { return 50; } }
        public override string ProtocolMethodName { get { return "queue.unbind"; } }
        public override bool HasContent { get { return false; } }

        public override void ReadArgumentsFrom(ArraySegmentSequence reader)
        {
            m_reserved1 = reader.ReadUInt16();
            m_queue = reader.ReadShortString();
            m_exchange = reader.ReadShortString();
            m_routingKey = reader.ReadShortString();
            m_arguments = reader.ReadTable();
        }

        public override void WriteArgumentsTo(FrameBuilder writer)
        {
            writer.WriteUInt16(m_reserved1);
            writer.WriteShortString(m_queue);
            writer.WriteShortString(m_exchange);
            writer.WriteShortString(m_routingKey);
            writer.WriteTable(m_arguments);
        }

        public override void AppendArgumentDebugStringTo(System.Text.StringBuilder sb)
        {
            sb.Append("(");
            sb.Append(m_reserved1); sb.Append(",");
            sb.Append(m_queue); sb.Append(",");
            sb.Append(m_exchange); sb.Append(",");
            sb.Append(m_routingKey); sb.Append(",");
            sb.Append(m_arguments);
            sb.Append(")");
        }
    }
}