// Autogenerated code. Do not edit.

// This source code is dual-licensed under the Apache License, version
// 2.0, and the Mozilla Public License, version 1.1.
//
// The APL v2.0:
//
//---------------------------------------------------------------------------
//   Copyright (c) 2007-2016 Pivotal Software, Inc.
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
//---------------------------------------------------------------------------
//
// The MPL v1.1:
//
//---------------------------------------------------------------------------
//   The contents of this file are subject to the Mozilla Public License
//   Version 1.1 (the "License"); you may not use this file except in
//   compliance with the License. You may obtain a copy of the License at
//   http://www.rabbitmq.com/mpl.html
//
//   Software distributed under the License is distributed on an "AS IS"
//   basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
//   License for the specific language governing rights and limitations
//   under the License.
//
//   The Original Code is RabbitMQ.
//
//   The Initial Developer of the Original Code is Pivotal Software, Inc.
//   Copyright (c) 2007-2016 Pivotal Software, Inc.  All rights reserved.
//---------------------------------------------------------------------------

using RabbitMQ.Client.Impl;
using RabbitMQ.Util;
namespace RabbitMQ.Client.Framing.Impl
{
    using RabbitMQ.Client.Framing;

    /// <summary>Autogenerated type. Private implementation class - do not use directly.</summary>
    public class QueueDeclareOk : RabbitMQ.Client.Impl.MethodBase, IQueueDeclareOk
    {
        public const ushort ClassId = 50;
        public const ushort MethodId = 11;

        public string m_queue;
        public uint m_messageCount;
        public uint m_consumerCount;

        string IQueueDeclareOk.Queue { get { return m_queue; } }
        uint IQueueDeclareOk.MessageCount { get { return m_messageCount; } }
        uint IQueueDeclareOk.ConsumerCount { get { return m_consumerCount; } }

        public QueueDeclareOk() { }
        public QueueDeclareOk(
          string initQueue,
          uint initMessageCount,
          uint initConsumerCount)
        {
            m_queue = initQueue;
            m_messageCount = initMessageCount;
            m_consumerCount = initConsumerCount;
        }

        public override ushort ProtocolClassId { get { return 50; } }
        public override ushort ProtocolMethodId { get { return 11; } }
        public override string ProtocolMethodName { get { return "queue.declare-ok"; } }
        public override bool HasContent { get { return false; } }

        public override void ReadArgumentsFrom(ArraySegmentSequence reader)
        {
            m_queue = reader.ReadShortString();
            m_messageCount = reader.ReadUInt32();
            m_consumerCount = reader.ReadUInt32();
        }

        public override void WriteArgumentsTo(FrameBuilder writer)
        {
            writer.WriteShortString(m_queue);
            writer.WriteUInt32(m_messageCount);
            writer.WriteUInt32(m_consumerCount);
        }

        public override void AppendArgumentDebugStringTo(System.Text.StringBuilder sb)
        {
            sb.Append("(");
            sb.Append(m_queue); sb.Append(",");
            sb.Append(m_messageCount); sb.Append(",");
            sb.Append(m_consumerCount);
            sb.Append(")");
        }
    }
}